name: Auto Merge PRs

on:
  pull_request:
    types:
      - labeled
      - synchronize
      - opened
      - reopened
      - ready_for_review

permissions:
  pull-requests: write
  contents: write

jobs:
  automerge:
    if: github.event.pull_request.merged == false && github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up GitHub CLI
        uses: cli/cli-action@v2

      - name: Attempt auto-merge
        run: |
          gh pr merge "$PR_URL" --merge --auto --delete-branch || echo "Merge not possible (conflicts or rules not met)"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
